consumer:
  username: lisi
  age: 23
  hobby: sing,read,sleep
  subject: 100,150


spring:
  profiles:
    active: pro
---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80
---

spring:
  config:
    activate:
      on-profile: test
server:
  port: 81
---

spring:
  config:
    activate:
      on-profile: pro
server:
  port: 82